name: Build and push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies with Yarn
        run: yarn

      - name: Process Lighthouse reports to generate reports.json
        run: yarn process-reports

      - name: Build the static website
        run: yarn build
        env:
          LIGHTHOUSE_RELATIVE_URL: /cfgov-lighthouse

      - name: Commit site back to GitHub
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
