name: Build static site

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - run: yarn build

      - name: Commit reports back to GitHub
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
