name: Build and push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies with Yarn
        run: yarn

      - name: Process Lighthouse reports to generate reports.json
        run: yarn process-reports

      - name: Build the static website
        run: yarn build
        env:
          LIGHTHOUSE_RELATIVE_URL: /cfgov-lighthouse

      - name: Commit site back to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs
          commit_message: Site rebuild triggered by commit
