name: Run Lighthouse, build, and push

on:
  # Run every night at midnight UTC.
  schedule:
    - cron: '0 0 * * *'

jobs:
  lhci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - run: yarn lighthouse

      - run: yarn index-reports

      - name: Commit reports and site back to GitHub
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
